EXTRA_CFLAGS += -std=gnu99
EXTRA_CFLAGS += -Werror
EXTRA_CFLAGS += -Wextra
EXTRA_CFLAGS += -Wno-declaration-after-statement
EXTRA_CFLAGS += -Wno-unused-parameter
EXTRA_CFLAGS += -Wno-missing-field-initializers

# Suppress some kernel error messages
EXTRA_CFLAGS += -Wno-empty-body
EXTRA_CFLAGS += -Wno-sign-compare

obj-m := amc525_lamc_priv.o

amc525_lamc_priv-objs += amc525_lamc_pci_core.o

# vim: set filetype=make:
