EXTRA_CFLAGS += -std=gnu99

# We can't enable as many warnings as I'd like for the kernel, but let's see
# what we can do.
EXTRA_CFLAGS += -Werror
EXTRA_CFLAGS += -Wextra
EXTRA_CFLAGS += -Wall

EXTRA_CFLAGS += -Wundef
EXTRA_CFLAGS += -Wcast-align
EXTRA_CFLAGS += -Wmissing-prototypes
EXTRA_CFLAGS += -Wmissing-declarations
EXTRA_CFLAGS += -Wstrict-prototypes

# Suppress some kernel error messages
EXTRA_CFLAGS += -Wno-declaration-after-statement
EXTRA_CFLAGS += -Wno-unused-parameter
EXTRA_CFLAGS += -Wno-missing-field-initializers
EXTRA_CFLAGS += -Wno-empty-body
EXTRA_CFLAGS += -Wno-sign-compare

EXTRA_CFLAGS += -DVERSION=$(VERSION)


obj-m := amc_pci.o

amc_pci-objs += amc_pci_core.o
amc_pci-objs += dma_control.o
amc_pci-objs += interrupts.o
amc_pci-objs += memory.o
amc_pci-objs += registers.o
amc_pci-objs += debug.o

# vim: set filetype=make:
