#!/usr/bin/env bash

# The following commands (run as root) force the PCI bus to be rescanned so that
# I/O memory windows can be successfully assigned to the PCI device.  Procedure
# reported here:
# https://www.linuxquestions.org/questions/linux-kernel-70/\
#   kernel-fails-to-assign-memory-to-pcie-device-4175487043/

# Ensure we're running as root
if (( $EUID != 0 )); then exec sudo "$0" "$@"; fi

# Find the first bridge that is connected to the bridge entering the
# MCH PCIe bridge
for b1 in /sys/devices/pci0000:00/*; do
    for b2 in ${b1}/*; do
        if [[ -f ${b2}/vendor ]]; then
            vendor=$(cat ${b2}/vendor)
            if [[ $vendor = 0x10b5 ]]; then
                echo "Found target bridge ${b1}"
                target_bridge="$b1"
                break 2
            fi
        fi
    done
done

if [[ -z "${target_bridge}" ]]; then
    echo "Target bridge not found"
    exit 1
fi

echo -n "Removing device "
echo 1 > "${target_bridge}"/remove
while [[ -e "${target_bridge}" ]]; do
    echo -n .
    sleep 0.5
done
echo

echo "Rescanning pci bus"
echo 1 > /sys/bus/pci/rescan
